FROM nvcr.io/nvidia/cuda:12.1.1-devel-ubuntu20.04

WORKDIR /root/main

RUN apt update
RUN apt install -y curl
RUN apt install -y vim
RUN curl -sL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get install -y nodejs
RUN apt update
